// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HabitCategory = "Health" | "Fitness" | "Productivity" | "Learning" | "Social" | "Finance" | "Study" | "Morning" | "Day" | "Night" | "Other" | "None";
