// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Habit = { name: string, description: string, created: string, color: string, progress: number, completion_count: number, };
